# Generated by Django 2.1.15 on 2020-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl2Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNumber', models.CharField(default=0, max_length=50)),
                ('PatientID', models.IntegerField(default=0)),
                ('HealthCenterID', models.IntegerField(default=0)),
                ('ConsulatedBy', models.IntegerField(default=0)),
                ('Fee', models.IntegerField(default=0)),
                ('RegisterDate', models.DateField()),
            ],
        ),
    ]
