# Generated by Django 2.1.15 on 2020-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200613_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl2cases',
            name='ConsulatedBy',
            field=models.CharField(default='', max_length=500),
        ),
    ]
