# Generated by Django 2.1.15 on 2020-06-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200613_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl2cases',
            name='tbl2consultants',
        ),
        migrations.RemoveField(
            model_name='tbl2cases',
            name='tbl2healthcenters',
        ),
        migrations.RemoveField(
            model_name='tbl2cases',
            name='tbl2patientstbl2consultants',
        ),
        migrations.AlterField(
            model_name='tbl2cases',
            name='ConsulatedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tbl2Consultants'),
        ),
        migrations.AlterField(
            model_name='tbl2cases',
            name='HealthCenterID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tbl2HealthCenters'),
        ),
        migrations.AlterField(
            model_name='tbl2cases',
            name='PatientID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tbl2Patients'),
        ),
    ]
